### PR TITLE
Use copilot.api and hide getPanelCompletions

### PR DESCRIPTION
**Pull request by MunifTanjim**
Replace custom implementation with `copilot.api` module.

Fix integration for `opts.method` = `"getPanelCompletions"`

### CODE REVIEW

**Review by zbirenbaum — COMMENTED** [review]
This PR has a lot of good changes like fixing the config and migrating the cycling handlers to use the ones provided by copilot.lua api, but unless your experience is very different from mine (which is possible, please do confirm this), panel completions should probably just be removed at least from the docs for now. Making it accessible again will probably cause a lot of  confusion and issues.

After testing it here and on master with the undocumented `completion_fn`, panel completions are still way too slow to be used for cmp-style completions, often 10+ seconds of leaving my cursor pretty still. This went unnoticed for so long because of panel completion slowdowns making it unusable. The changes that broke the method parameter were made back when I was trying different handler implementations in hopes of finding a way to speed it back up...

Its really sad because back when I wrote the implementation replaced here, it was actually faster than cycling completions and gave much better results. Unfortunately microsoft kept making changes that slowed it down so much the `method` configuration being broken actually reduced the volume of issue posts I think.

**Comment by MunifTanjim** [comment]
> but unless your experience is very different from mine

Nah, it's the same. It's a hit or miss, mostly miss. Most of the times I don't get anything at all, the time to receive suggestion is way too long.

**Comment by MunifTanjim** [comment]
> panel completions should probably just be removed at least from the docs for now.

Yep, done.

**Review by zbirenbaum — APPROVED** [review]
Looks perfect!

**Pull request merged**
